services:
  web:
    image: docker.io/node:20.9.0-alpine3.18
    container_name: hintable-web
    environment:
      - ORIGIN=http://localhost:5173
    ports:
      - '4173:4173'
    env_file:
      - .env
    volumes:
      - ./:/app
      - /app/node_modules/
      - /app/.pnpm-store/
    working_dir: /app
    command: sh -c "npm i -g pnpm@8.12.1 && pnpm install && pnpm run db:deploy && pnpm run build && pnpm run preview --host"
    depends_on:
      - db
  db:
    image: docker.io/postgres:13
    restart: always
    container_name: hintable-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db      
    ports:
      - '5432:5432'
    volumes:
      - /var/lib/postgresql/data