services:
  web:
    image: node:20.9.0-alpine3.18
    container_name: hintable
    environment:
      - CODESPACES
      - ORIGIN=http://localhost:6969
    ports:
      - '6969:6969'
    env_file:
      - .env
    volumes:
      - ./:/app
      - /app/node_modules/
      - /app/.pnpm-store/
    working_dir: /app
    command: sh -c "npm i -g pnpm && pnpm install && pnpm npx prisma migrate deploy && pnpm build && pnpm preview --port=6969"