name: Run Tests
'on':
  push:
    branches: main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: Install dependencies
        run: |
          yarn
          yarn playwright install
      - name: test and build
        env:
          BASE_PATH: '/${{ github.event.repository.name }}'
        run: |
          yarn test
          yarn build
      
